import 'package:flutter/material.dart';

///Color Scheme which corresponds to the App Theme color
///Colors used throughtout the app --> primary, secondary, tertiary
const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  //Defines the Primary Color
  primary: Color(0xFF6F35A5),
  //Defines the secondary color
  secondary: Color(0xFFF0E6FF),
  //Defines the Tertiary color
  tertiary: Color(0xFF6F35A5),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFF0DBFF),
  onPrimaryContainer: Color.fromRGBO(44, 0, 80, 1),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFE9DDFF),
  onSecondaryContainer: Color(0xFF23005C),

  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFF1DBFF),
  onTertiaryContainer: Color(0xFF2D0050),
  error: Color(0xFFBA1A1A),
  errorContainer: Color(0xFFFFDAD6),
  onError: Color(0xFFFFFFFF),
  onErrorContainer: Color(0xFF410002),
  background: Color(0xFFFFFBFF),
  onBackground: Color(0xFF1D1B1E),
  surface: Color(0xFFFFFBFF),
  onSurface: Color(0xFF1D1B1E),
  surfaceVariant: Color(0xFFE9DFEB),
  onSurfaceVariant: Color(0xFF4A454E),
  outline: Color(0xFF7C757E),
  onInverseSurface: Color(0xFFF6EFF4),
  inverseSurface: Color(0xFF322F33),
  inversePrimary: Color(0xFFDEB7FF),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF7B42B1),
  outlineVariant: Color(0xFFCDC4CE),
  scrim: Color(0xFF000000),
);

const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFFDEB7FF),
  onPrimary: Color(0xFF4A0080),
  primaryContainer: Color(0xFF622698),
  onPrimaryContainer: Color(0xFFF0DBFF),
  secondary: Color(0xFFD0BCFF),
  onSecondary: Color(0xFF381E72),
  secondaryContainer: Color(0xFF4F378A),
  onSecondaryContainer: Color(0xFFE9DDFF),
  tertiary: Color(0xFFDEB7FF),
  onTertiary: Color(0xFF44196A),
  tertiaryContainer: Color(0xFF5C3382),
  onTertiaryContainer: Color(0xFFF1DBFF),
  error: Color(0xFFFFB4AB),
  errorContainer: Color(0xFF93000A),
  onError: Color(0xFF690005),
  onErrorContainer: Color(0xFFFFDAD6),
  background: Color(0xFF1D1B1E),
  onBackground: Color(0xFFE7E1E5),
  surface: Color(0xFF1D1B1E),
  onSurface: Color(0xFFE7E1E5),
  surfaceVariant: Color(0xFF4A454E),
  onSurfaceVariant: Color(0xFFCDC4CE),
  outline: Color(0xFF968E98),
  onInverseSurface: Color(0xFF1D1B1E),
  inverseSurface: Color(0xFFE7E1E5),
  inversePrimary: Color(0xFF7B42B1),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFFDEB7FF),
  outlineVariant: Color(0xFF4A454E),
  scrim: Color(0xFF000000),
);
